spring:
  application:
    name: comeeatme-backend

  profiles:
    active: local, private

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/comeeatme?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop   # validate 로 추후 변경
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    open-in-view: false

  flyway:
    enabled: false
    baseline-on-migrate: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${OAUTH2_KAKAO_CLIENT_ID}
            client-secret: ${OAUTH2_KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope: ~
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

aws:
  paramstore:
    name: comeeatme
    enabled: true
    prefix: /config
    profile-separator: _

logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY}

kakao:
  local:
    base-url: https://dapi.kakao.com
    keyword-query-path: /v2/local/search/keyword.json
    category-query-path: /v2/local/search/category.json
