version: "3.8"

services:
  db:
    container_name: comeeatme-db
    image: arm64v8/mysql:8.0.28-oracle  # Mac m1 칩인 경우
#    image: mysql:8.0.28-oracle
    ports:
      - "3306:3306"
    environment:
      TZ: Asiz/Seoul
      MYSQL_DATABASE: comeeatme
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci