spring:
  application:
    name: comeeatme-backend

  profiles:
    active: local

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${OAUTH2_KAKAO_CLIENT_ID}
            client-secret: ${OAUTH2_KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope: ~
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

kakao:
  local:
    base-url: https://dapi.kakao.com
    keyword-query-path: /v2/local/search/keyword.json
    category-query-path: /v2/local/search/category.json

---
spring:
  config:
    activate:
      on-profile: local

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

  datasource:
    url: jdbc:mysql://localhost:3306/comeeatme?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao

  flyway:
    enabled: true
    baseline-on-migrate: true

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_S3_BUCKET}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    stack:
      auto: false

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
      apache.coyote.http11: debug

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY}

---
spring:
  config:
    activate:
      on-profile: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

  datasource:
    url: jdbc:mysql://${DATABASE_URL_DEV}/${DATABASE_NAME_DEV}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DATABASE_USERNAME_DEV}
    password: ${DATABASE_PASSWORD_DEV}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 500
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: https://api.cem.zooneon.dev/login/oauth2/code/kakao

  flyway:
    enabled: true
    baseline-on-migrate: true

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_S3_BUCKET_DEV}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    stack:
      auto: false

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
    root: debug

jwt:
  secret: ${JWT_SECRET_DEV}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY_DEV}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY_DEV}