spring:
  profiles:
    active: local

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    open-in-view: false

  batch:
    job:
      enabled: true
      names: 'AddressCodeFileDownloadJob'
    jdbc:
      initialize-schema: never
      isolation-level-for-create: default

open-api:
  business-juso:
    base-url: https://business.juso.go.kr
    road-address:
      path: /addrlink/addrLinkApi.do
      key: ${BUSINESS_JUSO_ROAD_ADDRESS_KEY}
    coord:
      path: /addrlink/addrCoordApi.do
      key: ${BUSINESS_JUSO_COORD_KEY}
  local-data:
    base-url: http://www.localdata.go.kr
    path: /platform/rest/TO0/openDataApi
    key: ${LOCAL_DATA_KEY}

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/comeeatme?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password:

  sql:
    init:
      mode: never

  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace

---
spring:
  config:
    activate:
      on-profile: dev
